# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
            ],
        ),
        migrations.CreateModel(
            name='FieldCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='condition_')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experto.Field', verbose_name='Campo')),
            ],
        ),
        migrations.CreateModel(
            name='FieldOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tipo de campo')),
            ],
        ),
        migrations.CreateModel(
            name='FieldType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tipo de campo')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Resultado')),
                ('conditions', models.ManyToManyField(to='experto.FieldCondition', verbose_name='Condiciones')),
            ],
        ),
        migrations.AddField(
            model_name='field',
            name='field_option',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Opciones', to='experto.FieldOption'),
        ),
        migrations.AddField(
            model_name='field',
            name='field_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_campo', to='experto.FieldType', verbose_name='Tipo de campo'),
        ),
    ]
