# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experto', '0002_auto_20161124_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='field_option',
        ),
        migrations.AddField(
            model_name='field',
            name='field_option',
            field=models.ManyToManyField(default=0, related_name='Opciones', to='experto.FieldOption'),
        ),
    ]
