# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experto', '0006_auto_20161124_2304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={'ordering': ('my_order',)},
        ),
        migrations.AddField(
            model_name='field',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fieldcondition',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Condicion'),
        ),
    ]
